---
apiVersion: v1
kind: Secret
metadata:
  name: aws-creadential
  namespace: update-asg
type: Opaque
stringData:
  ACCESS_KEY: 'AKIAUXKJWWMEVXN63PPO'
  SECRET_KEY: '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'
  REGION_NAME: 'ap-southeast-1'