---
apiVersion: v1
kind: Service
metadata:
  name: update-asg-svc
  namespace: update-asg
spec:
  selector:
    app: update-asg
  ports:
    - name: http
      port: 5555
      targetPort: 5555
      nodePort: 31111
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-asg-deployment
  namespace: update-asg
  labels:
    app: update-asg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: update-asg
  template:
    metadata:
      labels:
        app: update-asg
    spec:
      containers:
      - name: update-asg
        image: phanminhlam/update-asg
        envFrom:
        - secretRef:
            name: aws-creadential